<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="API.com.project.api.SAIL.SAIL_JobPlacements" tests="8" time="3.601" ignored="0" failures="3" timestamp="05 Sep 2017 20:30:15 GMT" skipped="0" hostname="WFXD481D7D98814" errors="0">
  <testcase name="T1_test_Http_Status_Code_For_The_Programs_API" time="2.193" classname="API.com.project.api.SAIL.SAIL_JobPlacements"/>
  <testcase name="T5_test_Check_A_SpecificRecord" time="0.516" classname="API.com.project.api.SAIL.SAIL_JobPlacements"/>
  <testcase name="T4_test_OffSet_And_Max_When_Set_To_Some_Value_Records_Are_Displayed_While_Using_Pagesize" time="0.184" classname="API.com.project.api.SAIL.SAIL_JobPlacements">
    <failure type="java.lang.AssertionError" message="Expected and Actual Status code didn&#039;t match expected [200] but found [500]">
      <![CDATA[java.lang.AssertionError: Expected and Actual Status code didn't match expected [200] but found [500]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:389)
	at RestAssureHelper.RestAssuredHelper.assertStatusCodeForResponse(RestAssuredHelper.java:94)
	at API.com.project.api.SAIL.SAIL_JobPlacements.T4_test_OffSet_And_Max_When_Set_To_Some_Value_Records_Are_Displayed_While_Using_Pagesize(SAIL_JobPlacements.java:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- T4_test_OffSet_And_Max_When_Set_To_Some_Value_Records_Are_Displayed_While_Using_Pagesize -->
  <testcase name="T8_test_No_Of_Records_If_OfSet_IS_SET_TO_0" time="0.112" classname="API.com.project.api.SAIL.SAIL_JobPlacements">
    <failure type="java.lang.AssertionError" message="Expected and Actual Status code didn&#039;t match expected [200] but found [500]">
      <![CDATA[java.lang.AssertionError: Expected and Actual Status code didn't match expected [200] but found [500]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:389)
	at RestAssureHelper.RestAssuredHelper.assertStatusCodeForResponse(RestAssuredHelper.java:94)
	at API.com.project.api.SAIL.SAIL_JobPlacements.T8_test_No_Of_Records_If_OfSet_IS_SET_TO_0(SAIL_JobPlacements.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- T8_test_No_Of_Records_If_OfSet_IS_SET_TO_0 -->
  <testcase name="T2_test_All_Headers_Are_Present_In_The_Response" time="0.003" classname="API.com.project.api.SAIL.SAIL_JobPlacements"/>
  <testcase name="T7_test_No_Of_Records_If_Offset_And_Max_Are_Same" time="0.069" classname="API.com.project.api.SAIL.SAIL_JobPlacements">
    <failure type="java.lang.AssertionError" message="Expected and Actual Status code didn&#039;t match expected [200] but found [500]">
      <![CDATA[java.lang.AssertionError: Expected and Actual Status code didn't match expected [200] but found [500]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:389)
	at RestAssureHelper.RestAssuredHelper.assertStatusCodeForResponse(RestAssuredHelper.java:94)
	at API.com.project.api.SAIL.SAIL_JobPlacements.T7_test_No_Of_Records_If_Offset_And_Max_Are_Same(SAIL_JobPlacements.java:172)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- T7_test_No_Of_Records_If_Offset_And_Max_Are_Same -->
  <testcase name="T6_test_Check_Records_In_Range" time="0.523" classname="API.com.project.api.SAIL.SAIL_JobPlacements"/>
  <testcase name="T3_test_More_Than_Records_Are_Returned_From_The_Call" time="0.001" classname="API.com.project.api.SAIL.SAIL_JobPlacements"/>
</testsuite> <!-- API.com.project.api.SAIL.SAIL_JobPlacements -->
